### ISSUE TITLE
Tools is Not working now?

### ISSUE THREAD

**Issue by nikhilpatel4** [MrSp4rX/iSpammer#8]

**Comment by MrSp4rX** [comment]
I really apologise for that but due to some people who clone our tool and make it running for infinite times and this is why tool isn’t working anymore and this repository is not maintained by us now.

**Comment by nikhilpatel4** [comment]
> I really apologise for that but due to some people who clone our tool and make it running for infinite times and this is why tool isn’t working anymore and this repository is not maintained by us now.

Ok bro no problem 🙂.
